### ISSUE TITLE
Can Not Download

### ISSUE THREAD

**Issue by Neuturrican** [rchenwh1te/StreamDownloader#3]
I'm using your amazing application on MyFidelio.
I thank you so much.

But, I can not download Siegfried (1992) only.
This is probably because the VIDEO and AUDIO values ​​are both -30.
If it is possible to rewrite the database, please do so.

Sorry for my poor English.

**Comment by rchenwh1te** [comment]
I have fixed the bug, now uploading the fixed version. Just to give you the instructions on how to implement it - are you using Windows or Linux? Did you use an installer?

**Comment by Neuturrican** [comment]
Thank you for your very quick response.
I'm using Windows and used the installer.
I replaced database.db in StreamDownloader / media / with a new one, but StreamDownloader no longer starts.
Fail to execute script __main__ is displayed.
Am I doing it wrong?

**Comment by rchenwh1te** [comment]
1. Download media/database.db from the repository
2. Copy it over to your installation path under "media"
3. Tell me if it still doesn't work

**Comment by Neuturrican** [comment]
I followed the steps, but I still can't start the application.
The old database.db is 73728 bytes and the new database.db is 151770 bytes. Is this the correct file?
I downloaded a new file from within <> CODE.

**Comment by rchenwh1te** [comment]
It is not the right file. Here's a link to the correct one:
https://github.com/rchenwh1te/StreamDownloader/blob/master/media/database.db

**Comment by Neuturrican** [comment]
Thank you very much.
I was new to Github and downloaded a different file.
Insert the correct file, launch the application, and SIEGFRIED is fine too.
Thank you again for your kindness.

**Comment by emrothenberg** [comment]
Hi, I know I'm late to the party, but does either of you have access to the videos? I've been going all over the internet looking for an archive
